Data:
  batch_size: 128
  input_dim: 9
  name: Peptides-struct
  output_dim: 10
  train_frac: 0.8
  val_frac: 0.1
Device: cuda
Model:
  dropout_frac: 0.0
  encoder: Atom
  framework: MeMP
  hidden_dim: 64
  hops: 5
  type: GCN
Optimizer:
  eval_after_epoch: 2
  learning_rate: 0.001
  lr_decay_factor: 0.8
  type: AdamW
  weight_decay: 1e-5
Scheduler:
  mode: min
  name: reduce_lr_on_plateau
  reduce_factor: 0.5
Train:
  loss_fn: l1
  max_epoches: 200
  metric: mae
